"""Add program coordinator, attendance, and feedback calendar fields

Revision ID: 239b13d794d3
Revises: 36f550b17e6e
Create Date: 2026-08-18 12:30:15.781562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '239b13d794d3'
down_revision: Union[str, Sequence[str], None] = '36f550b17e6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('program_coordinators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_program_coordinators_employee_id'), 'program_coordinators', ['employee_id'], unique=True)
    op.create_index(op.f('ix_program_coordinators_id'), 'program_coordinators', ['id'], unique=False)
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('academic_year_id', sa.Integer(), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.Column('division_id', sa.Integer(), nullable=False),
    sa.Column('total_classes', sa.Integer(), nullable=True),
    sa.Column('classes_attended', sa.Integer(), nullable=True),
    sa.Column('attendance_percentage', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], ),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.id'], ),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'subject_id', 'academic_year_id', 'semester_id', name='uq_student_attendance_cycle')
    )
    op.create_index(op.f('ix_attendance_id'), 'attendance', ['id'], unique=False)
    op.add_column('evaluation_cycles', sa.Column('start_datetime', sa.DateTime(timezone=True), nullable=True))
    op.add_column('evaluation_cycles', sa.Column('end_datetime', sa.DateTime(timezone=True), nullable=True))
    op.add_column('evaluation_cycles', sa.Column('scope', sa.String(length=100), nullable=True))
    op.add_column('evaluation_cycles', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('evaluation_cycles', sa.Column('timezone', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'evaluation_cycles', 'users', ['created_by'], ['id'])
    op.add_column('faculty_subjects', sa.Column('division_id', sa.Integer(), nullable=True))
    op.create_unique_constraint('uq_faculty_subject_assignment', 'faculty_subjects', ['faculty_id', 'subject_id', 'academic_year_id', 'division_id'])
    op.create_foreign_key(None, 'faculty_subjects', 'divisions', ['division_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'faculty_subjects', type_='foreignkey')
    op.drop_constraint('uq_faculty_subject_assignment', 'faculty_subjects', type_='unique')
    op.drop_column('faculty_subjects', 'division_id')
    op.drop_constraint(None, 'evaluation_cycles', type_='foreignkey')
    op.drop_column('evaluation_cycles', 'timezone')
    op.drop_column('evaluation_cycles', 'created_by')
    op.drop_column('evaluation_cycles', 'scope')
    op.drop_column('evaluation_cycles', 'end_datetime')
    op.drop_column('evaluation_cycles', 'start_datetime')
    op.drop_index(op.f('ix_attendance_id'), table_name='attendance')
    op.drop_table('attendance')
    op.drop_index(op.f('ix_program_coordinators_id'), table_name='program_coordinators')
    op.drop_index(op.f('ix_program_coordinators_employee_id'), table_name='program_coordinators')
    op.drop_table('program_coordinators')
    # ### end Alembic commands ###
