"""Add analytics summary tables

Revision ID: 36f550b17e6e
Revises: c1a8a72bd47a
Create Date: 2026-08-17 16:30:03.893698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36f550b17e6e'
down_revision: Union[str, Sequence[str], None] = 'c1a8a72bd47a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('college_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('average_rating', sa.Float(), nullable=True),
    sa.Column('total_responses', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_college_summaries_id'), 'college_summaries', ['id'], unique=False)
    op.create_table('department_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('average_rating', sa.Float(), nullable=True),
    sa.Column('total_responses', sa.Integer(), nullable=True),
    sa.Column('faculty_count', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_department_summaries_department_id'), 'department_summaries', ['department_id'], unique=True)
    op.create_index(op.f('ix_department_summaries_id'), 'department_summaries', ['id'], unique=False)
    op.create_table('faculty_subject_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('average_rating', sa.Float(), nullable=True),
    sa.Column('response_count', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faculty_subject_summaries_department_id'), 'faculty_subject_summaries', ['department_id'], unique=False)
    op.create_index(op.f('ix_faculty_subject_summaries_faculty_id'), 'faculty_subject_summaries', ['faculty_id'], unique=False)
    op.create_index(op.f('ix_faculty_subject_summaries_id'), 'faculty_subject_summaries', ['id'], unique=False)
    op.create_index(op.f('ix_faculty_subject_summaries_subject_id'), 'faculty_subject_summaries', ['subject_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_faculty_subject_summaries_subject_id'), table_name='faculty_subject_summaries')
    op.drop_index(op.f('ix_faculty_subject_summaries_id'), table_name='faculty_subject_summaries')
    op.drop_index(op.f('ix_faculty_subject_summaries_faculty_id'), table_name='faculty_subject_summaries')
    op.drop_index(op.f('ix_faculty_subject_summaries_department_id'), table_name='faculty_subject_summaries')
    op.drop_table('faculty_subject_summaries')
    op.drop_index(op.f('ix_department_summaries_id'), table_name='department_summaries')
    op.drop_index(op.f('ix_department_summaries_department_id'), table_name='department_summaries')
    op.drop_table('department_summaries')
    op.drop_index(op.f('ix_college_summaries_id'), table_name='college_summaries')
    op.drop_table('college_summaries')
    # ### end Alembic commands ###
